Traceback (most recent call last):
  File "/Users/emilylloyd/miniconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/emilylloyd/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilylloyd/miniconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilylloyd/miniconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/emilylloyd/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/emilylloyd/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/emilylloyd/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data=pd.read_csv("/Users/emilylloyd/Documents/Coding Course/analysis_book/Data/demo.csv")

pd.read_csv("https://github.com/CaitlinLloyd/Psychology_Programming2025/blob/main/Data/demo.csv")
------------------


[31m---------------------------------------------------------------------------[39m
[31mParserError[39m                               Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 3[39m
[32m      1[39m data=pd.read_csv([33m"[39m[33m/Users/emilylloyd/Documents/Coding Course/analysis_book/Data/demo.csv[39m[33m"[39m)
[32m----> [39m[32m3[39m [43mpd[49m[43m.[49m[43mread_csv[49m[43m([49m[33;43m"[39;49m[33;43mhttps://github.com/CaitlinLloyd/Psychology_Programming2025/blob/main/Data/demo.csv[39;49m[33;43m"[39;49m[43m)[49m

[36mFile [39m[32m~/miniconda3/lib/python3.12/site-packages/pandas/io/parsers/readers.py:1026[39m, in [36mread_csv[39m[34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)[39m
[32m   1013[39m kwds_defaults = _refine_defaults_read(
[32m   1014[39m     dialect,
[32m   1015[39m     delimiter,
[32m   (...)[39m[32m   1022[39m     dtype_backend=dtype_backend,
[32m   1023[39m )
[32m   1024[39m kwds.update(kwds_defaults)
[32m-> [39m[32m1026[39m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

[36mFile [39m[32m~/miniconda3/lib/python3.12/site-packages/pandas/io/parsers/readers.py:626[39m, in [36m_read[39m[34m(filepath_or_buffer, kwds)[39m
[32m    623[39m     [38;5;28;01mreturn[39;00m parser
[32m    625[39m [38;5;28;01mwith[39;00m parser:
[32m--> [39m[32m626[39m     [38;5;28;01mreturn[39;00m [43mparser[49m[43m.[49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m

[36mFile [39m[32m~/miniconda3/lib/python3.12/site-packages/pandas/io/parsers/readers.py:1923[39m, in [36mTextFileReader.read[39m[34m(self, nrows)[39m
[32m   1916[39m nrows = validate_integer([33m"[39m[33mnrows[39m[33m"[39m, nrows)
[32m   1917[39m [38;5;28;01mtry[39;00m:
[32m   1918[39m     [38;5;66;03m# error: "ParserBase" has no attribute "read"[39;00m
[32m   1919[39m     (
[32m   1920[39m         index,
[32m   1921[39m         columns,
[32m   1922[39m         col_dict,
[32m-> [39m[32m1923[39m     ) = [38;5;28;43mself[39;49m[43m.[49m[43m_engine[49m[43m.[49m[43mread[49m[43m([49m[43m  [49m[38;5;66;43;03m# type: ignore[attr-defined][39;49;00m
[32m   1924[39m [43m        [49m[43mnrows[49m
[32m   1925[39m [43m    [49m[43m)[49m
[32m   1926[39m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[32m   1927[39m     [38;5;28mself[39m.close()

[36mFile [39m[32m~/miniconda3/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py:234[39m, in [36mCParserWrapper.read[39m[34m(self, nrows)[39m
[32m    232[39m [38;5;28;01mtry[39;00m:
[32m    233[39m     [38;5;28;01mif[39;00m [38;5;28mself[39m.low_memory:
[32m--> [39m[32m234[39m         chunks = [38;5;28;43mself[39;49m[43m.[49m[43m_reader[49m[43m.[49m[43mread_low_memory[49m[43m([49m[43mnrows[49m[43m)[49m
[32m    235[39m         [38;5;66;03m# destructive to chunks[39;00m
[32m    236[39m         data = _concatenate_chunks(chunks)

[36mFile [39m[32mparsers.pyx:838[39m, in [36mpandas._libs.parsers.TextReader.read_low_memory[39m[34m()[39m

[36mFile [39m[32mparsers.pyx:905[39m, in [36mpandas._libs.parsers.TextReader._read_rows[39m[34m()[39m

[36mFile [39m[32mparsers.pyx:874[39m, in [36mpandas._libs.parsers.TextReader._tokenize_rows[39m[34m()[39m

[36mFile [39m[32mparsers.pyx:891[39m, in [36mpandas._libs.parsers.TextReader._check_tokenize_status[39m[34m()[39m

[36mFile [39m[32mparsers.pyx:2061[39m, in [36mpandas._libs.parsers.raise_parser_error[39m[34m()[39m

[31mParserError[39m: Error tokenizing data. C error: Expected 1 fields in line 42, saw 62


